var shoes = [
        {
            'id' : 100,
            'color' : 'blue',
            brand : 'Mike'
            price : 350,
            size : 7,
            in_stock : 5
        },
        {
            id : 101,
            color : 'green',
            brand : 'Mike'
            price : 350,
            size : 8,
            in_stock : 5
        },
        {
            id : 123;
            color : 'orange',
            brand : "Abi"
            price : 275,
            size : 5,
            in_stock : 3
        }
];
